version: "3"
services:
  app:
    image: "${CONTAINER_IMAGE}"
    volumes:
      - "/root/config/kit/.env.js:/app/.env.js"
      # - "/root/config/kit/.env-${STAGE}.js:/app/.env.js"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==public]
    environment:
      INSTANCE: "{{.Task.Slot}}"
      DOCKER_IMAGE: "${DOCKER_IMAGE}"
      STAGE: "${STAGE}"
      CONTAINER_IMAGE: "${CONTAINER_IMAGE}"
      VERSION: "${CI_COMMIT_SHA}"

      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: devops@isuvorov.ru
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthcheck"]
      # start_period: 15s
    networks:
      # - local
      - proxy


networks:
  local:
  proxy:
    external:
      name: nginx-proxy
